name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile Test document
        uses: xu-cheng/latex-action@master
        with:
          root_file: test.tex
      - name: Compile with graphviz
        uses: xu-cheng/latex-action@master
        with:
          root_file: graphviz_test.tex
          working_directory: tests/
          extra_packages: arara
          # openjdk11 is used by arara
          # ttf-freefont is used by graphviz.
          extra_system_packages: "graphviz openjdk11-jre ttf-freefont"
          compiler: arara
          args: "--verbose"
      - name: Compile fduthesis document
        uses: xu-cheng/latex-action@master
        with:
          root_file: fduthesis.tex
          args: "-xelatex -file-line-error -interaction=nonstopmode"
          extra_packages: "adobemapping amsfonts amsmath arphic-ttf babel-japanese baekmuk biber biblatex biblatex-gb7714-2015 bibtex caption cm ctablestack ctex currfile dvipdfmx environ etex etoolbox fancyhdr fandol filehook fontspec footmisc gbt7714 geometry graphics graphics-cfg graphics-def hyperref ifluatex ifxetex ipaex japanese-otf kantlipsum knuth-lib l3build l3experimental l3kernel l3packages latex-bin latexmk libertinus-fonts lm lm-math logreq lualatex-math lualibs luaotfload luatex luatex85 luatexbase luatexja metafont mfware ms natbib ntheorem oberdiek pgf platex platex-tools preview psnfss ptex ptex-base ptex-fontmaps ptex-fonts siunitx standalone symbol tex tex-gyre tex-gyre-math tex-ini-files tools trimspaces ucharcat ulem unicode-data unicode-math uplatex uptex uptex-base uptex-fonts url varwidth xcolor xecjk xetex xits xkeyval xstring xunicode zapfding zhlipsum zhmetrics-uptex zhnumber fduthesis"
      # - name: Compile fduthesis with graphviz
      # uses: xu-cheng/latex-action@master
      # with:
      #   root_file: main
      #   args: "-xelatex -shell-escape"
      #   extra_packages: "graphviz adobemapping amsfonts amsmath arphic-ttf babel-japanese baekmuk biber biblatex biblatex-gb7714-2015 bibtex caption cm ctablestack ctex currfile dvipdfmx environ etex etoolbox fancyhdr fandol filehook fontspec footmisc gbt7714 geometry graphics graphics-cfg graphics-def hyperref ifluatex ifxetex ipaex japanese-otf kantlipsum knuth-lib l3build l3experimental l3kernel l3packages latex-bin latexmk libertinus-fonts lm lm-math logreq lualatex-math lualibs luaotfload luatex luatex85 luatexbase luatexja metafont mfware ms natbib ntheorem oberdiek pgf platex platex-tools preview psnfss ptex ptex-base ptex-fontmaps ptex-fonts siunitx standalone symbol tex tex-gyre tex-gyre-math tex-ini-files tools trimspaces ucharcat ulem unicode-data unicode-math uplatex uptex uptex-base uptex-fonts url varwidth xcolor xecjk xetex xits xkeyval xstring xunicode zapfding zhlipsum zhmetrics-uptex zhnumber fduthesis"
      #   extra_system_packages: "graphviz"
      - name: copy
        run: |
          mkdir -p public
          cp -r test.pdf public/test.pdf
          cp -r fduthesis.pdf public/fduthesis.pdf
          cp -r main.pdf public/main.pdf
          cp -r tests/graphviz_test.pdf public/graphviz_test.pdf
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
        with:
          emptyCommits: true
