name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile Test document
        uses: xu-cheng/latex-action@master
        with:
          root_file: test.tex
      - name: test
        run: |
          ls ~
          pwd
          whoami
          ls /opt/texlive/texdir/
          cp /opt/texlive/texmf-var/fonts/conf/texlive-fontconfig.conf /etc/fonts/conf.d/09-texlive.conf
          fc-cache -fsv
      - name: Compile fduthesis document
        uses: xu-cheng/latex-action@master
        with:
          root_file: fduthesis.tex
          args: "-xelatex -file-line-error -interaction=nonstopmode"
          extra_packages: "footmisc ctex zhnumber amsfonts fontspec libertinus-fonts metafont ptex-fontmaps ptex-fonts uptex-fonts ntheorem fduthesis"
      - name: copy
        run: |
          mkdir -p public
          cp -r test.pdf public/test.pdf
          cp -r fduthesis.pdf public/fduthesis.pdf
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
        with:
          emptyCommits: true
