name: Build LaTeX document
on: 
  push: 
    branches:
    - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: test.tex
      - name: ls
        run: | 
          ls
          git status
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./